<?php
return array (
  'alert_opt_out.conversation_message_reaction' => 'Reacts to your message in a conversation',
  'alert_opt_out.post_forumwatch_insert' => 'Posts in a watched forum',
  'alert_opt_out.post_insert' => 'Trả lời chủ đề đã theo dõi',
  'alert_opt_out.post_like' => 'Thích bài viết của bạn',
  'alert_opt_out.post_mention' => 'Nhắc đến bạn trong một tin nhắn',
  'alert_opt_out.post_quote' => 'Trích dẫn bài viết của bạn',
  'alert_opt_out.post_reaction' => 'Reacts to your message',
  'alert_opt_out.profile_post_comment_like' => 'Thích bình luận trên bài viết trong hồ sơ của bạn',
  'alert_opt_out.profile_post_comment_other_commenter' => 'Có bình luận về bài viết trong hồ sơ',
  'alert_opt_out.profile_post_comment_reaction' => 'Reacts to your profile post comment',
  'alert_opt_out.profile_post_comment_your_post' => 'Bình luận về hồ sơ của bạn cho các thành viên khác',
  'alert_opt_out.profile_post_comment_your_profile' => 'Bình luận về hồ sơ hoặc trạng thái của bạn',
  'alert_opt_out.profile_post_insert' => 'Đăng trên hồ sơ của bạn',
  'alert_opt_out.profile_post_like' => 'Thích bài viết trên hồ sơ của bạn',
  'alert_opt_out.profile_post_mention' => 'Nhắc đến bạn trong bài viết hồ sơ hoặc bình luận',
  'alert_opt_out.profile_post_reaction' => 'Reacts to your profile post',
  'alert_opt_out.resource_rating_reply' => 'Replies to your resource review',
  'alert_opt_out.resource_rating_review' => 'Reviews your resource',
  'alert_opt_out.resource_update_insert' => 'Updates a watched resource',
  'alert_opt_out.resource_update_mention' => 'Đề cập đến bạn trong một tài nguyên',
  'alert_opt_out.resource_update_reaction' => 'Reacts to your resource',
  'alert_opt_out.trophy_award' => 'Nhận danh hiệu mới',
  'alert_opt_out.user_following' => 'Bắt đầu theo dõi bạn',
);