<?php
return array (
  'permission_interface.BR_ModernStatistics' => 'Brivium - Modern statistics permisisons',
  'permission_interface.XGT_istatistik_izin_grubu' => '[XGT] Forum istatistikleri - izinleri',
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.border' => 'Border',
  'permission_interface.conversationModeratorPermissions' => 'Conversation Moderator Permissions',
  'permission_interface.conversationPermissions' => 'Quyền đối thoại',
  'permission_interface.forumModeratorPermissions' => 'Quyền kiểm duyệt viên diễn đàn',
  'permission_interface.forumPermissions' => 'Quyền diễn đàn',
  'permission_interface.generalModeratorPermissions' => 'Quyền kiểm duyệt viên chung',
  'permission_interface.generalPermissions' => 'Quyền chung',
  'permission_interface.postAttachmentPermissions' => 'Post Attachment Permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile Post Moderator Permissions',
  'permission_interface.profilePostPermissions' => 'Profile Post Permissions',
  'permission_interface.resourceModeratorPermissions' => 'Resource moderator permissions',
  'permission_interface.resourcePermissions' => 'Resource permissions',
  'permission_interface.signaturePermissions' => 'Signature Permissions',
  'permission_interface.th_uix' => 'UI.X Permissions',
  'permission_interface.th_unco' => '[TH] User Name Color permissions',
);