<?php
return array (
  'widget_def.birthdays' => 'Today\'s birthdays',
  'widget_def.find_member' => 'Tìm thành viên',
  'widget_def.forum_statistics' => 'Thống kê diễn đàn',
  'widget_def.html' => 'HTML',
  'widget_def.member_stat' => 'Member stat',
  'widget_def.members_online' => 'Thành viên trực tuyến',
  'widget_def.new_posts' => 'New posts',
  'widget_def.new_profile_posts' => 'New profile posts',
  'widget_def.new_threads' => 'New threads',
  'widget_def.newest_members' => 'Thành viên mới',
  'widget_def.online_statistics' => 'Online statistics',
  'widget_def.php_callback' => 'Hàm PHP',
  'widget_def.share_page' => 'Chia sẻ trang',
  'widget_def.template_syntax' => 'Template syntax',
  'widget_def.th_post_thread_uix' => '[UI.X] Start a thread',
  'widget_def.th_widget_login_uix' => '[UI.X] Login form',
  'widget_def.thread_poll' => 'Thread poll',
  'widget_def.thuix_socialMedia' => '[TH] UI.X social media feed',
  'widget_def.visitor_panel' => 'Bảng khách truy cập',
  'widget_def.xfrm_latest_reviews' => 'XFRM: Latest reviews',
  'widget_def.xfrm_new_resources' => 'XFRM: New resources',
  'widget_def.xfrm_top_resources' => 'XFRM: Top Resources',
  'widget_def.xgtForumIstKullanici_wd' => '[XGT] Forum istatistik - En çok mesaj',
);